proxy:
  https:
    hosts:
      - jday-orsay.jovyan.org
    letsencrypt:
      contactEmail: benjaminrk@gmail.com

auth:
  type: github
  github:
    callbackUrl: "https://jday-orsay.jovyan.org/hub/oauth_callback"
  admin:
    users:
      - choldgraf
      - minrk

singleuser:
  image:
    name: jupyter/scipy-notebook
    tag: 92fe05d1e7e5

