proxy:
  https:
    hosts:
      - jday-orsay.jovyan.org
    letsencrypt:
      contactEmail: benjaminrk@gmail.com

auth:
  type: github
  github:
    callbackUrl: "https://jday-orsay.jovyan.org/hub/oauth_callback"
  admin:
    users:
      - choldgraf
      - minrk

singleuser:
  fsGid: 0

  image:
    name: jupyter/scipy-notebook
    tag: 92fe05d1e7e5
  extraEnv:
    DOCKER_HOST: unix:///var/run/dind/docker.sock
  storage:
    extraVolumes:
      - name: dind
        hostPath:
          path: /var/run/dind
    extraVolumeMounts:
      - name: dind
        mountPath: /var/run/dind

