proxy:
  https:
    hosts:
      - jday-orsay.jovyan.org
    letsencrypt:
      contactEmail: benjaminrk@gmail.com

auth:
  type: github
  github:
    callbackUrl: "https://jday-orsay.jovyan.org/hub/oauth_callback"
  admin:
    users:
      - choldgraf
      - minrk

singleuser:
  cpu:
    limit: 2
  memory:
    limit: 2G
    guarantee: 1G
  fsGid: 0
  image:
    name: minrk/jupyter-day-2018
    tag: latest
  extraEnv:
    DOCKER_HOST: unix:///var/run/dind/docker.sock
  storage:
    extraVolumes:
      - name: dind
        hostPath:
          path: /var/run/dind
    extraVolumeMounts:
      - name: dind
        mountPath: /var/run/dind

